title: Erkan EREN
description: Software Engineer (BSc.) 34349
socials:
    -
      url: https://linkedin.com/in/erkan-eren
      text: linkedin/erkan-eren
      icon: /assets/images/linkedin.png
    -
      url: https://github.com/ErkanEREN/
      text: github@ErkanEREN
      icon: /assets/images/github.png

theme: "jekyll-theme-slate"
github:
  is_project_page: false
  is_user_page: true