title: Erkan EREN
description: Software Engineer (BSc.) 34349
action:
  url: https://erkaneren.dev/linkedin
  text: linkedin.com/in/erkan-eren
  icon: https://content.linkedin.com/content/dam/me/brand/en-us/brand-home/logos/In-Blue-Logo.png.original.png
LinkedIn: https://erkaneren.dev/linkedin
theme: "jekyll-theme-slate"
github:
  is_project_page: false
  is_user_page: true